### ISSUE TITLE
fall back to MSR crypto IFF window.crypto.getRandomValues is undefined

### ISSUE THREAD

**Issue by diracdeltas** [brave/vault-client#2]
MSR crypto seems to be using their own PRNG regardless of whether window.crypto.getRandomValues is available. Since random number generation is important and easy to backdoor, i think we should only fallback to MSR crypto for getRandomValues when window.crypto.getRandomValues is undefined.

**Comment by mrose17** [comment]
i contacted the library authors about that XHR issue, and haven't heard back (yet).
i think there are two issues:

first, even if there is a good PRNG available, that (inactive) XHR code still gets called ... the code does check for:

        /// If window.{crypto,msCrypto}.getRandomValues() function is present, do not register mouse and JS load events,
        /// because they slow down the execution, and it is not clear how much they contributed over and above
        /// a cryptographic random value.

so, i think we just need some scrubbing

second, under node we want `require('crypto').randomBytes` ... i should have seen that one coming.

**Comment by diracdeltas** [comment]
For now, please just add a wrapper around MSR's getRandomValues that checks if window.{msCrypto,crypto}.getRandomValues is defined and uses that if so.
